# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 9000:9000
