# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

services:
  lebkuchen-fm:
    build:
      context: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017
    ports:
      - 9000:9000
    networks:
      - lebkuchen-network
    depends_on:
     - mongo
  mongo:
    container_name: lebkuchen-fm-db-local
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - lebkuchen-network

networks:
  lebkuchen-network:
    driver: bridge
