ktor:
  application:
    modules:
      - xyz.lebkuchenfm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

storage:
  mongodb:
    connectionString: "$MONGODB_URL:mongodb://localhost:27017"
  dropbox:
    auth:
      refreshToken: "$DROPBOX_REFRESH_TOKEN"
      appKey: "$DROPBOX_APP_KEY"
      appSecret: "$DROPBOX_APP_SECRET"
    paths:
      xSounds: "$DROPBOX_X_SOUNDS_PATH:/xsounds/"
