ktor:
  application:
    modules:
      - xyz.lebkuchenfm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

storage:
  mongodb:
    connectionString: "$MONGODB_URI:mongodb://localhost:27017"

security:
  encryptionKey: $SECRET_ENCRYPTION_KEY
