ktor:
  application:
    modules:
      - xyz.lebkuchenfm.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

storage:
  mongodb:
    connectionString: "$MONGODB_URI:mongodb://localhost:27017"
  dropbox:
    auth:
      refreshToken: $?DROPBOX_REFRESH_TOKEN
      appKey: $?DROPBOX_CLIENT_ID
      appSecret: $?DROPBOX_SECRET
    paths:
      xSounds: "$DROPBOX_X_SOUNDS_PATH:/xsounds/"

youtube:
  apiKey: $?YOUTUBE_API_KEY

discord:
  token: $?DISCORD_TOKEN
  channelId: $?DISCORD_CHANNEL_ID

commandPrompt: "$COMMAND_PROMPT:/fm"

radioPersonality:
  textToSpeech:
    gcp:
      apiKey: $?GCP_TTS_API_KEY
      languageCode: "$GCP_TTS_LANG:en-US"
      voiceGender: "$GCP_TTS_VOICE_GENDER:NEUTRAL"
      speakingRate: "$GCP_TTS_SPEAKING_RATE:1.0"
