name: Build

on: [push]

jobs:
  runtime_versions:
    strategy:
      matrix:
        node-version: [18.x]
        jdk-version: [23]

  build-v2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: yarn install --frozen-lockfile
    - run: yarn run build
    - run: yarn test

  build-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk-version }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      - name: Build backend service
        run: ./gradlew build

      - name: Install client dependencies
        run: yarn install --frozen-lockfile

      - name: Build client
        run: yarn run build:client-beta

      - name: Test client
        run: yarn run test:client-beta
