name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Deploy on production
          if: github.ref == 'refs/heads/main'
          run: flyctl deploy --remote-only --no-cache --app lebkuchen-fm
        - name: Deploy on dev
          if: github.ref != 'refs/heads/main'
          run: flyctl deploy --remote-only --no-cache --app lebkuchen-fm-dev
