name: Lint Client Beta

on:
  push:
    paths:
      - 'packages/client-beta/**'
  pull_request:
    paths:
      - 'packages/client-beta/**'

  lint-client-beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: yarn install --frozen-lockfile
    - run: yarn lint:client-beta
    - run: yarn format:check:client-beta
